### ISSUE TITLE
Issues Tracking Spreadsheet Proposal

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/futureautomations#17]
### Overview 
Allow issues created on a GitHub repo to be automatically exported into a Google Spreadsheet

### Ownership of Idea
- [ ] I will be working on this automation myself
- [ ] This is my idea and I need help developing it
- [x] Free for anyone to work on this idea

### Current State 
You can use Zapier to do this, but it does not effectively update the spreadsheet when an issue is updated. It only creates a new line on the spreadsheet when the issue is created.

### Stakeholders
This would be a great tool for teams to track their progress on open issues and also build work breakdown schedules, track OKRs, Milestones more effectively

### Resources/Instructions
Check out the Zapier google sheets and github integration options

### Automation triggers (What starts it? What's it responding to?)
event based - everytime an issue is created or updated on a GitHub repo

### Input required (How much manual or custom input is required?)
The trigger should be based on what actions are taken on an issue such as adding a label, closing an issue

### Output 
_(What's the desired result? What do we not want to see?)_
Updating an issue automatically updates its state in the spreadsheet
